import { Inter, } from "next/font/google";
import type { Metadata } from "next";

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter",
});

// const robotoMono = Roboto_Mono({
// 	subsets: ["latin"],
// 	variable: "--font-roboto-mono",
// });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	
	
	return (
		<html lang="en">
			<head>
				<meta
					name="format-detection"
					content="telephone=no, date=no, email=no, address=no"
				/>
			</head>
			<body className={`${inter.variable}`}>
				{children}
			</body>
		</html>
	);
}