/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/models/f1-car/oracle_red_bull_f1_car_rb19_2023.glb -t 
Author: Redgrund (https://sketchfab.com/redgrund)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/oracle-red-bull-f1-car-rb19-2023-e4afe46f3aab4b23a418da06fc163821
Title: Oracle Red Bull F1 Car RB19 2023
*/
'use client';

import * as THREE from 'three'

import React, { JSX } from 'react'

import { GLTF } from 'three-stdlib'
import { useGLTF } from '@react-three/drei'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
  }
  materials: {
    Full_Body_Baked: THREE.MeshPhysicalMaterial
  }
  // animations: GLTFAction[]
}

export function F1RedBull(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/assets/models/f1-car/oracle_red_bull_f1_car_rb19_2023.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.138, 0.324]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Full_Body_Baked} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Full_Body_Baked} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Full_Body_Baked} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Full_Body_Baked} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Full_Body_Baked} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Full_Body_Baked} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Full_Body_Baked} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/f1-car/oracle_red_bull_f1_car_rb19_2023.glb')
